### ISSUE TITLE
After rating a song as 7, skip does not work

### ISSUE THREAD

**Issue by daubman** [dprodger/dynplay#5]
Works:
1) Enter Artist, click "Let's Go" button
2) Click radio button for rating of anything but 7 for the first song
3) Observe rating is sent
4) Click "Skip" button
5) observe that song is skipped and next song is played

Returns 500 Internal Server error from api when attempting to get next song after rating:
1) Enter Artist, click "Let's Go" button
2) Click radio button for rating of 7 for the first song
3) Observe rating is sent
4) Click "Skip" button
5) Console shows 500 Internal server error returned from API - appears to be an API issue?

**Comment by dprodger** [comment]
This is a server-side bug right now -- when we rate songs, we use their acoustic properties; some songs don't have this, so the playlist code errors out.

Tyler is theoretically deploying a fix today or tomorrow.

**Comment by dprodger** [comment]
Resolved with song attribute server-side fix
